// Project Euler 2: Even Fibonacci Numbers:
// Prompt: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting  with 1 and 2, the first terms will be:
// 1,2,3,5,8,13,21,34,55,89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.
public class pe_02 {
    public static void main(String[] args) {
        int x = 0, y = 1, sum = 0, temp = 0;

        do {
            if(y % 2 == 0) {
                sum += y;
            }
            temp = x + y;
            x = y;
            y = temp;

        } while (y < 4000000);

        System.out.print(sum);


    }
}